namespace Domain.Enums;

public enum PermissionType
{
    GetPlants,
    GetPlantById,
    SavePlants,
    ModifyPlants,
    DeletePlants,
    RecognizePlants,
    GetRankedPlants,
    GetHealthAssesments,
    GetHealthAssesmentById,
    DoHealthAssesments,
    GetRiskAlerts,
    Login,
    ResetPassword,
    RecoverPassword,
    ChangePassword,
    GetUsers,
    GetUserById,
    AddUser,
    UpdateUser,
    DeleteUser,
    GetGroups,
    GetGroupById,
    AddGroup,
    UpdateGroup,
    DeleteGroup,
    GetScansAmount,
    GetHealthyPlantsAmount,
    GetCreatedUsersAmount,
    GetLoginsAmount,
    GetWateringCalendar,
    GetPermissions,
}